platform.version=@platformVersion@
slf4j.version=@slf4jVersion@
junit.jupiter.version=@junitJupiterVersion@
assertj.version=@assertjVersion@
java.toolchain.version=@javaToolchainVersion@
gradle.version=@gradleVersion@
